[build]
  command = "npm run build"
  publish = ".next"
  environment = { PYTHON_VERSION = "3.13" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
  external_node_modules = []

[[plugins]]
  package = "@netlify/plugin-nextjs"